services:
  initialize_app:
    platform: linux/amd64
    build: .
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - .:/skullrax
    environment:
      - DATABASE_URL=postgresql://hyrax_user:hyrax_password@postgres/hyrax_development
      - DATABASE_TEST_URL=postgresql://hyrax_user:hyrax_password@postgres/hyrax_test
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=hyrax_user
      - DB_PASSWORD=hyrax_password
      - DB_NAME=hyrax_development
      - FCREPO_HOST=fcrepo
      - FCREPO_PORT=8080
      - FCREPO_REST_PATH=rest
      - HYRAX_VALKYRIE=true
      - RAILS_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/0
      - SEED_DASSIE=true
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_URL=http://solr:8983/solr/hydra-development
      - VALKYRIE_STORAGE_ADAPTER=versioned_disk_storage
      - VALKYRIE_TRANSITION=true
    depends_on:
      - postgres
      - solr
      - redis
      - fcrepo
    command: /skullrax/bin/initialize-app.sh

  web:
    platform: linux/amd64
    build: .
    entrypoint: ["/bin/sh", "-c"]
    user: root
    ports:
      - "3000:3000"
    volumes:
      - .:/skullrax
      - uploads:/app/samvera/hyrax-webapp/public/uploads
      - derivatives:/app/samvera/hyrax-webapp/tmp/derivatives
      - tmp:/app/samvera/hyrax-webapp/tmp
      - storage:/app/samvera/hyrax-webapp/storage
    command: >
      "mkdir -p /app/samvera/hyrax-webapp/tmp/pids &&
       rm -f /app/samvera/hyrax-webapp/tmp/pids/* &&
       sleep infinity"
    depends_on:
      initialize_app:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      solr:
        condition: service_started
      redis:
        condition: service_started
      fcrepo:
        condition: service_started
      chrome:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://hyrax_user:hyrax_password@postgres/hyrax_development
      - DATABASE_TEST_URL=postgresql://hyrax_user:hyrax_password@postgres/hyrax_test
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=hyrax_user
      - DB_PASSWORD=hyrax_password
      - DB_NAME=hyrax_development
      - FCREPO_HOST=fcrepo
      - FCREPO_PORT=8080
      - FCREPO_REST_PATH=rest
      - HYRAX_VALKYRIE=true
      - RAILS_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/0
      - SE_DRIVER_URL=http://chrome:4444/wd/hub
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_URL=http://solr:8983/solr/hydra-development
      - VALKYRIE_STORAGE_ADAPTER=versioned_disk_storage
      - VALKYRIE_TRANSITION=true

  worker:
    platform: linux/amd64
    build: .
    entrypoint: []
    user: root
    volumes:
      - .:/skullrax
      - uploads:/app/samvera/hyrax-webapp/public/uploads
      - derivatives:/app/samvera/hyrax-webapp/tmp/derivatives
      - tmp:/app/samvera/hyrax-webapp/tmp
      - storage:/app/samvera/hyrax-webapp/storage
    command: sleep infinity
    depends_on:
      initialize_app:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      solr:
        condition: service_started
      redis:
        condition: service_started
      fcrepo:
        condition: service_started
    environment:
      - CH12N_TOOL=fits_servlet
      - DATABASE_URL=postgresql://hyrax_user:hyrax_password@postgres/hyrax_development
      - DATABASE_TEST_URL=postgresql://hyrax_user:hyrax_password@postgres/hyrax_test
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=hyrax_user
      - DB_PASSWORD=hyrax_password
      - DB_NAME=hyrax_development
      - FCREPO_HOST=fcrepo
      - FCREPO_PORT=8080
      - FCREPO_REST_PATH=rest
      - FITS_SERVLET_URL=http://fits:8080/fits
      - HYRAX_VALKYRIE=true
      - RAILS_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/0
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_URL=http://solr:8983/solr/hydra-development
      - VALKYRIE_STORAGE_ADAPTER=versioned_disk_storage
      - VALKYRIE_TRANSITION=true

  fits:
    image: ghcr.io/samvera/fitsservlet:1.6.0
    ports:
      - "8081:8080"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hyrax_user
      POSTGRES_PASSWORD: hyrax_password
      POSTGRES_DB: hyrax_development
    volumes:
      - db:/var/lib/postgresql/data

  solr:
    image: solr:8.11
    ports:
      - "8983:8983"
    volumes:
      - ./solr/conf:/opt/solr/server/configsets/hyraxconf
      - solr_home:/var/solr
    command: >
      sh -c "precreate-core hydra-test /opt/solr/server/configsets/hyraxconf;
             solr-precreate hydra-development /opt/solr/server/configsets/hyraxconf"

  redis:
    image: redis:alpine

  chrome:
    image: selenium/standalone-chromium:4
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_SESSION_TIMEOUT=800
      - SE_ENABLE_TRACING=false

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    ports:
      - 8080:8080

volumes:
  db:
  solr_home:
  uploads:
  derivatives:
  tmp:
  storage:
